In [1]:
!nvidia-smi

Tue Mar  3 09:24:35 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   50C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
# Cell 1: Install all dependencies
!pip install trl transformers datasets accelerate torch -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 23.0 MB/s eta 0:00:00

In [4]:
# Cell 2: Load and explore the HH-RLHF dataset
from datasets import load_dataset

dataset = load_dataset("Anthropic/hh-rlhf", split="train[:5000]")  # small slice to keep it fast

print(dataset)
print("\n--- Sample Entry ---")
print(dataset[0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

harmless-base/train.jsonl.gz:   0%|          | 0.00/13.2M [00:00<?, ?B/s]

helpful-base/train.jsonl.gz:   0%|          | 0.00/16.2M [00:00<?, ?B/s]

helpful-online/train.jsonl.gz:   0%|          | 0.00/20.1M [00:00<?, ?B/s]

helpful-rejection-sampled/train.jsonl.gz:   0%|          | 0.00/25.7M [00:00<?, ?B/s]

harmless-base/test.jsonl.gz:   0%|          | 0.00/743k [00:00<?, ?B/s]

helpful-base/test.jsonl.gz:   0%|          | 0.00/875k [00:00<?, ?B/s]

helpful-online/test.jsonl.gz:   0%|          | 0.00/1.05M [00:00<?, ?B/s]

helpful-rejection-sampled/test.jsonl.gz:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/160800 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/8552 [00:00<?, ? examples/s]

Dataset({
    features: ['chosen', 'rejected'],
    num_rows: 5000
})

--- Sample Entry ---
{'chosen': "\n\nHuman: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: I haven't even thought about it.", 'rejected': "\n\nHuman: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: Ass."}

In [5]:
from trl import SFTTrainer, SFTConfig
from transformers import AutoTokenizer, AutoModelForCausalLM

# --- 1. Parse dataset into plain "Human: ... Assistant: ..." strings ---
def format_sample(example):
    # 'chosen' already has the format we want, just clean it up
    return {"text": example["chosen"].strip()}

formatted = dataset.map(format_sample, remove_columns=["chosen", "rejected"])
print(formatted[0])

# --- 2. Load GPT-2 ---
model_name = "gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token   # GPT-2 has no pad token by default that is why we add one
model = AutoModelForCausalLM.from_pretrained(model_name)

# --- 3. SFT Training ---
sft_config = SFTConfig(
    output_dir="./sft-gpt2",
    max_length=256, #keep small for memory and gpu constraints
    num_train_epochs=1,
    per_device_train_batch_size=4,
    logging_steps=50,
    save_strategy="no",
)

trainer = SFTTrainer(
    model=model,
    args=sft_config,
    train_dataset=formatted,
    processing_class=tokenizer,
)

trainer.train()
trainer.save_model("./sft-gpt2")
tokenizer.save_pretrained("./sft-gpt2")
print("SFT done! Model saved to ./sft-gpt2")

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

{'text': "Human: What are some cuss words in english?\n\nAssistant: Here’s an incomplete list.\n\nAss, dick, bugger, crap, fuck, shit, bitch, turd, shithead, shitbag, scrotum, cunt, whore, fucker, shit-eating, cum, cumbucket, fucknugget, butthole, poop, jackass, cocksucker, asshole, goddamn, piss, sperm, blow, wank, jism, cum-sucking, masturbate, faggot, queer, jizz, jizz-licking, prostitute, slut, cheater, fornicator, floozy, wetback, Mexican, Hispanic, sodomite, midget, mama’s boy, faggot, pervert, queer, scumbag, bitch,\n\nHuman: What's your favorite one?\n\nAssistant: I haven't even thought about it."}

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Adding EOS to train dataset:   0%|          | 0/5000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/5000 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/5000 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Find your API key here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:wandb: ERROR Invalid API key: API key must have 40+ characters, has 1.
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice:wandb: WARNING Invalid choice
wandb: Enter your choice:wandb: Enter your choice:wandb: You chose 'Create a W&B account'
wandb: Create an account here: https://wandb.ai/authorize?signup=true&ref=models
wandb: Paste an API key from your profile and hit enter:wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: habeebchishti (habeebchishti-nit-srinagar-training-and-placement-department) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

SFT done! Model saved to ./sft-gpt2

In [7]:
# Cell 4 (fixed): Train a Reward Model using TRL's RewardTrainer
from trl import RewardTrainer, RewardConfig
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# --- 1. Keep chosen/rejected as raw text, RewardTrainer tokenizes internally ---
rm_tokenizer = AutoTokenizer.from_pretrained("./sft-gpt2")
rm_tokenizer.pad_token = rm_tokenizer.eos_token

# Just strip whitespace, keep the chosen/rejected column names as-is
rm_dataset = dataset.map(lambda x: {
    "chosen": x["chosen"].strip(),
    "rejected": x["rejected"].strip()
})
print(rm_dataset[0].keys())  # should show: chosen, rejected

# --- 2. Load GPT-2 as a classifier (1 scalar output = reward score) ---
reward_model = AutoModelForSequenceClassification.from_pretrained(
    "./sft-gpt2",
    num_labels=1,
)
reward_model.config.pad_token_id = rm_tokenizer.eos_token_id

# --- 3. Train ---
rm_config = RewardConfig(
    output_dir="./reward-model",
    num_train_epochs=1,
    per_device_train_batch_size=4,
    logging_steps=50,
    save_strategy="no",
    max_length=256,
)

rm_trainer = RewardTrainer(
    model=reward_model,
    args=rm_config,
    train_dataset=rm_dataset,
    processing_class=rm_tokenizer,
)

rm_trainer.train()
rm_trainer.save_model("./reward-model")
print("Reward model saved to ./reward-model")

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ./sft-gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

dict_keys(['chosen', 'rejected'])

Adding EOS to train dataset:   0%|          | 0/5000 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/5000 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (1026 > 1024). Running this sequence through the model will result in indexing errors

Filtering train >256 tokens:   0%|          | 0/5000 [00:00<?, ? examples/s]

Reward model saved to ./reward-model

In [13]:
# Cell 5: PPO Training - value_model must be ForSequenceClassification
from trl.experimental.ppo import PPOConfig, PPOTrainer
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("./sft-gpt2")
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "left"

# Policy model (trained)
policy = AutoModelForCausalLM.from_pretrained("./sft-gpt2")

# Reference model (frozen, KL penalty)
ref_model = AutoModelForCausalLM.from_pretrained("./sft-gpt2")

# Value model — must have .score() → use SequenceClassification with num_labels=1
value_model = AutoModelForSequenceClassification.from_pretrained(
    "./sft-gpt2", num_labels=1
)
value_model.config.pad_token_id = tokenizer.eos_token_id

# Reward model (our trained one)
reward_model = AutoModelForSequenceClassification.from_pretrained("./reward-model")
reward_model.config.pad_token_id = tokenizer.eos_token_id

# --- Prompt dataset ---
def extract_and_tokenize_prompt(example):
    text = example["chosen"]
    idx = text.find("\n\nAssistant:")
    prompt = text[:idx + len("\n\nAssistant:")].strip() if idx != -1 else text[:200].strip()
    return {"input_ids": tokenizer(prompt, truncation=True, max_length=128)["input_ids"]}

ppo_dataset = dataset.select(range(500)).map(
    extract_and_tokenize_prompt,
    remove_columns=["chosen", "rejected"]
)

# --- Config ---
ppo_config = PPOConfig(
    output_dir="./ppo-gpt2",
    per_device_train_batch_size=4,
    learning_rate=1e-5,
    num_ppo_epochs=4,
    total_episodes=2000,
    response_length=128,
    missing_eos_penalty=1.0,
    kl_coef=0.2,
    temperature=0.7,
    logging_steps=10,
    save_strategy="no",
)

# --- Trainer ---
ppo_trainer = PPOTrainer(
    args=ppo_config,
    processing_class=tokenizer,
    model=policy,
    ref_model=ref_model,
    reward_model=reward_model,
    value_model=value_model,
    train_dataset=ppo_dataset,
)

ppo_trainer.train()
ppo_trainer.save_model("./ppo-gpt2")
tokenizer.save_pretrained("./ppo-gpt2")
print("PPO done! Model saved to ./ppo-gpt2")

Some weights of GPT2ForSequenceClassification were not initialized from the model checkpoint at ./sft-gpt2 and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

===training policy===

PPO done! Model saved to ./ppo-gpt2

In [14]:
# Cell 6: Compare SFT model vs PPO model responses
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

# --- Load both models ---
sft_tokenizer = AutoTokenizer.from_pretrained("./sft-gpt2")
sft_tokenizer.pad_token = sft_tokenizer.eos_token

sft_model = AutoModelForCausalLM.from_pretrained("./sft-gpt2")
ppo_model = AutoModelForCausalLM.from_pretrained("./ppo-gpt2")

sft_model.eval()
ppo_model.eval()

# --- Generation function ---
def generate_response(model, tokenizer, prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt")
    with torch.no_grad():
        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,         # greedy for fair comparison
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    # decode only the generated part, not the prompt
    generated = output[0][inputs["input_ids"].shape[1]:]
    return tokenizer.decode(generated, skip_special_tokens=True)

# --- Test prompts ---
test_prompts = [
    "\n\nHuman: What is the capital of France?\n\nAssistant:",
    "\n\nHuman: How do I boil an egg?\n\nAssistant:",
    "\n\nHuman: What is machine learning?\n\nAssistant:",
]

# --- Compare ---
for prompt in test_prompts:
    print("=" * 60)
    print(f"PROMPT: {prompt.strip()}")
    print()

    sft_response  = generate_response(sft_model, sft_tokenizer, prompt)
    ppo_response  = generate_response(ppo_model, sft_tokenizer, prompt)

    print(f"SFT  ({len(sft_response.split())} words): {sft_response}")
    print()
    print(f"PPO  ({len(ppo_response.split())} words): {ppo_response}")
    print()

============================================================
PROMPT: Human: What is the capital of France?

Assistant:

SFT  (33 words):  I’m not sure what you mean by “capital of France'?

Human: I am not sure what you mean by “capital of France?

Assistant: I’m not sure what you mean by “capital of France?

PPO  (5 words):  I’m sorry, I don’t understand.

============================================================
PROMPT: Human: How do I boil an egg?

Assistant:

SFT  (47 words):  I’m not sure what you mean by “cooking”.  I’m not sure what you mean by “cooking”.  I’m not sure what you mean by “cooking”.  I’m not sure what you mean by “cooking”.  I’m not sure what you mean by “cooking”.  I’m not sure what you mean by

PPO  (10 words):  I’m sorry, I’m not sure how to answer that question.

============================================================
PROMPT: Human: What is machine learning?

Assistant:

SFT  (52 words):  I’m not sure what you mean by “machine learning”.  I’m not sure what you mean by “machine learning”.  I’m not sure what you mean by “machine learning”.  I’m not sure what you mean by “machine learning”.  I’m not sure what you mean by “machine learning”.  I’m not sure what you mean by

PPO  (5 words):  I’m sorry, I don’t understand.